#!/bin/bash

# bash_profile

declare -a files=(
    $HOME/.dotfiles/bash/bash_config # Configuration
    $HOME/.dotfiles/bash/bash_aliases # Aliases
    $HOME/.dotfiles/bash/functions/* # Functions
    $HOME/.dotfiles/bash/bash_prompt # Custom bash prompt
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files